name: webapp_deployment

description: deploys container on webapp

inputs:
  FLOW_TO_EXECUTE:
    description: "the flow to be registered and deployed"
    required: true
  DEPLOY_ENVIRONMENT:
    description: "env stage e.g. dev, test, prod"
    required: true


runs:
  using: composite
  steps:
    - name: prepare docker image
      uses: ./.github/actions/prepare_docker_image
      with:
        FLOW_TO_EXECUTE: ${{ inputs.FLOW_TO_EXECUTE }}
        DEPLOY_ENVIRONMENT: ${{ inputs.DEPLOY_ENVIRONMENT }}


    - name: create webapp
      shell: bash
      run: flow_to_execute=${{ inputs.FLOW_TO_EXECUTE }} deploy_environment=${{ inputs.DEPLOY_ENVIRONMENT }} build_id=${{ github.run_id }} ./llmops/common/scripts/az_webapp_deploy.sh 
