parameters:
- name: FLOW_TO_EXECUTE
  type: string
- name: DEPLOY_ENVIRONMENT
  type: string
- name: CONNECTION_DETAILS
  type: string
- name: REGISTRY_DETAILS
  type: string
steps:
- template: ./prepare_docker_image.yml
  parameters:
    FLOW_TO_EXECUTE: ${{ parameters.FLOW_TO_EXECUTE }}
    DEPLOY_ENVIRONMENT: ${{ parameters.DEPLOY_ENVIRONMENT }}
    CONNECTION_DETAILS: '${{ parameters.CONNECTION_DETAILS }}'
    REGISTRY_DETAILS: '${{ parameters.REGISTRY_DETAILS }}'

- task: AzureCLI@2
  displayName: Webapp deployment
  name: webapp_deployment
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      flow_to_execute=${{ parameters.FLOW_TO_EXECUTE }} deploy_environment=${{ parameters.DEPLOY_ENVIRONMENT }} build_id=$(Build.BuildNumber) CONNECTION_DETAILS='${{ parameters.CONNECTION_DETAILS }}' "./llmops/common/scripts/az_webapp_deploy.sh" 